[package]
name = "tweers-asset"
version = "1.0.0"
edition = "2024"
publish = false

[dependencies]
async-trait = "0.1.88"
tracing = "0.1"
tweers-core = { path = "../core", version = "1.0.0" }
tweers-core-full = { path = "../core-full", version = "1.0.0" }
zip = "7.2.0"
