[package]
name = "tweers-asset"
version = "0.1.20"
edition = "2024"
publish = false

[dependencies]
async-trait = "0.1.88"
tracing = "0.1"
tweers-core = { path = "../core", version = "0.1.20" }
tweers-core-full = { path = "../core-full", version = "0.1.20" }
zip = "7.2.0"
